TEP for Trim Task Result
XinruZhang/community pull request #1
Opened 2020-09-25 15:54 UTC by XinruZhang

2020-09-25 16:56 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +This lead to that the read-out content contains an extra end of file new line.
This isn't quite right I don't think - Tekton doesn't add newlines or EOFs.  Instead the command in the Step does it. For example:

```bash
# in a Task.spec.steps list
- image: alpine
  script: |
    echo "hello, world!" > /tekton/results/my-result
```

^ This use of `echo` adds a newline at the end of "hello, world!" and it is that newline character which ends up in the result data.  Many CLI tools similarly add newlines when they write to stdout.  But some do not.  Consider the following example:

```bash
- image: alpine
  script: |
    echo -n "hello, world!" > /tekton/results/my-result
```

This results in no extra newline.

2020-09-25 16:56 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +        - command:
you can use a `script` block here to help readability instead of `command` like this:

```yaml
steps:
- name: main
  image: alpine:3.12
  script: |
    echo "$(params.project_name)" > "$(results.project.path)"
```

2020-09-25 16:56 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +        - command:
similarly here, you can replace the array of command strings with a `script` block to help readers.

2020-09-25 16:56 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +- If the `TrimRegex` is an empty string, then trim all leading and tailing whitespaces of the result
I think "empty string" should do the same thing as "`TrimRegex` is not set" - do nothing to the result.

If the user wants to remove all leading and trailing whitespace then they can specify the regex `"^\s+|\s+$"`.

What do you think?

2020-09-25 16:56 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +The **goal 1** may effect existing Tasks and Pipelines who tackle the problem by themself.
I think it is important not to introduce a backwards-incompatible change if we can avoid it.  It might be preferable if the user can choose whether they want this behavior or not?

2020-09-25 16:56 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +fileContents = fileContents[:len(fileContents)-1]
As you mention later in this TEP this would break Tasks that already trim the last newline from their output.  It might be a bit safer to use `strings.TrimSuffix(fileContents, "\n")`?  This will only remove the last character if it is already a `\n` newline.

2020-09-28 04:52 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +This lead to that the read-out content contains an extra end of file new line.
Yes you are right!

2020-09-28 04:52 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +        - command:
Got it!

2020-09-28 04:55 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +- If the `TrimRegex` is an empty string, then trim all leading and tailing whitespaces of the result
That's great~

2020-09-28 05:01 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +The **goal 1** may effect existing Tasks and Pipelines who tackle the problem by themself.
Yes, I somehow fell into the wrong idea, which is reading the value from the result file will cause the extra newline, so I was thinking that strip the extra new line is a "must-do" thing.

2020-09-28 05:01 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +fileContents = fileContents[:len(fileContents)-1]
Yes!

2020-09-28 05:02 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +fileContents = fileContents[:len(fileContents)-1]
Thanks so much for your review!

2020-09-28 16:36 UTC, ImJasonH requested changes

2020-09-28 16:36 UTC, ImJasonH commented on teps/tep-trim-tekton-results.md
> +**Goal 2**: Provide a flexible way to trim unwanted leading and trailing characters of the results.
I think adding this goal expands the scope of the work further than any user has actually asked for, and complicates the API and implementation.

By my understanding, the request is just to be able to have Tekton trim _trailing whitespace_, and that should be very straightforward to satisfy with a new Boolean field, `TrimTrailingWhitespace`, rather than adding arbitrary regexp support to the API.

By adding regexp support, the common use case gets harder to express (users have to understand the regexp for "trailing whitespace"), and the use cases it enables aren't being asked for as far as I know.

If after we support `TrimTrailingWhitespace` some user wants `TrimLeadingWhitespace` or `TrimRegex` we can add those too with more context about their use case. But since nobody has asked for that yet I suspect no one will then either.

2020-09-29 11:21 UTC, XinruZhang commented on teps/tep-trim-tekton-results.md
> +**Goal 2**: Provide a flexible way to trim unwanted leading and trailing characters of the results.
Hi Jason, Thanks for your comment!

Yes, this may make things more complicated. However, adding a boolean field may not enough to handle some corner cases. Here is one: If the result value itself contains whitespaces at the tail, the TrimTrailingWhitespaces will wrongly delete them too.

2020-09-29 11:45 UTC, ImJasonH commented on teps/tep-trim-tekton-results.md
> +**Goal 2**: Provide a flexible way to trim unwanted leading and trailing characters of the results.
Is that a use case we've identified while we've been gathering requirements from users? My understanding was the main driving use case was eliminating newlines from the ends of results values that were unintentionally added, and couldn't be easily stripped by using shell commands, for example when the image doesn't have a shell.

If a user wants to apply a regex to transform their results values, they can already do so today by running another step that invokes `sed` or `awk`, or anything really, to modify the results value. This feature just aims to make that easier in the most common case of trimming trailing whitespace.

2020-09-29 17:14 UTC, sbwsg reviewed
Looks great Xinru.  Once you've made any remaining changes I think you should open a Pull Request in https://github.com/tektoncd/community/pulls !

2020-09-29 17:14 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +As for the example in the issue [#3146](https://github.com/tektoncd/pipeline/issues/3146), setting `TrimTrailingWhitespaces` field as `true` can solve the problem.
User stories typically have the format of "As a <user type> I want to <action description> so that <action result>."

In this case it might be something like this:

```
### User Story

As a Task author I want to trim the trailing whitespace from the
results generated by a container image that I do not control so
that I don't have to create a new container image just to remove
whitespace.
```

2020-09-29 17:14 UTC, sbwsg commented on teps/tep-trim-tekton-results.md
> +results:
This example is great.  I suggest moving it to the "Design Details" section, since it's specifying the exact syntax a task author will use.

2022-11-24 16:48 UTC, closed without merging